"""name

Revision ID: 043cdb4f6b28
Revises: ceef7b710f4d
Create Date: 2022-11-14 23:16:17.595762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043cdb4f6b28'
down_revision = 'ceef7b710f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
