"""name

Revision ID: 5b2bec91a032
Revises: d8e581cb9f9d
Create Date: 2022-11-14 22:10:33.073087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b2bec91a032'
down_revision = 'd8e581cb9f9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
