"""name

Revision ID: 79aed18c8f3b
Revises: 5b2bec91a032
Create Date: 2022-11-14 22:50:31.792797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79aed18c8f3b'
down_revision = '5b2bec91a032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
