"""name

Revision ID: ceef7b710f4d
Revises: 33cd3538c398
Create Date: 2022-11-14 23:11:23.719442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceef7b710f4d'
down_revision = '33cd3538c398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
