"""name

Revision ID: d5517a741ee4
Revises: 3e47d84615b5
Create Date: 2022-11-08 10:04:35.537678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5517a741ee4'
down_revision = '3e47d84615b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', postgresql.UUID(), nullable=True))
    op.drop_constraint('session_user_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['user_id'], ['id'])
    op.drop_column('session', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key('session_user_fkey', 'session', 'user', ['user'], ['id'])
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###
