"""name

Revision ID: e57d2272f6eb
Revises: 62a974e0630d
Create Date: 2022-11-08 15:25:41.791372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57d2272f6eb'
down_revision = '62a974e0630d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
